mysql:
  dsn: root@rea

redis:
  addr: localhost:6379

oss:
  us01:
    endpoint: https://***.aliyuncs.com
    access_key_id: clientId
    access_key_secret: ClientSecret

tracer:
 sample: 1
 stdout_enable: false